apiVersion: v1
kind: Service
metadata:
  name: ${app}-${type}
  labels:
    app: ${app}-${type}
spec:
  ports:
    - name: db 
      protocol: TCP
      port: 5432
      targetPort: 5432
  selector:
    app: ${app}-${type}
  type: NodePort
---
apiVersion: v1
kind: Service
metadata:
  name: ${app}-${type}-admin
  labels:
    app: ${app}-${type}
spec:
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: http
    - name: https
      protocol: TCP
      port: 443
      targetPort: https
  selector:
    app: ${app}-${type}

