kind: BuildConfig
apiVersion: build.openshift.io/v1
metadata:
  name: dbaas-1-0-1 
spec:
  nodeSelector: null
  output:
    to:
      kind: ImageStreamTag
      name: 'dbaas:1.0.1'
  resources: {}
  successfulBuildsHistoryLimit: 5
  failedBuildsHistoryLimit: 5
  strategy:
    type: Source
    sourceStrategy:
      from:
        kind: ImageStreamTag
        name: 'nodejs-14:latest'
  postCommit: {}
  source:
    type: Git
    git:
      uri: 'https://github.com/fdavalo/dbaas'
      ref: 1.0.1
  runPolicy: Serial
