apiVersion: apps/v1
kind: Deployment
metadata:
  name: dbaas-1-0-1 
  labels:
    app: dbaas-1-0-1 
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dbaas-1-0-1 
  template:
    metadata:
      labels:
        app: dbaas-1-0-1 
    spec:
      serviceAccountName: dbaas 
      containers:
      - name: web 
        image: image-registry.openshift-image-registry.svc:5000/dbaas:dbaas-1.0.1 
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
        args: ['/bin/sh', '/run/shared/start.sh']
        env:
          - name: REGIONS_LOCAL 
            value: "local cluster"
          - name: REGIONS_LOCAL_SC
            value: ocs-external-storagecluster-ceph-rbd
          - name: REGIONS_LOCAL_VSC
            value: ocs-external-storagecluster-rbdplugin-snapclass
        volumeMounts:
        - name: shared
          mountPath: '/opt/app-root/src/databases/data'
        - name: config-volume
          mountPath: '/run/shared'
      volumes:
      - name: shared
        emptyDir: {}
      - name: config-volume
        configMap:
          name: dbaas 

