kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: ${app}-${type}-pvc-${id} 
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: ${sc}
  volumeMode: Filesystem
  dataSource:
    apiGroup: snapshot.storage.k8s.io
    kind: VolumeSnapshot
    name: ${app}-${type}-${id} 

